"use client";
import { useEffect, useState } from "react";
import { Badge, RunDetails } from "@/components/run-details";
import type { Run } from "@/lib/types";

export default function DemoPage() {
  const [runs, setRuns] = useState<Run[]>([]); const [run, setRun] = useState<Run | null>(null); const [working, setWorking] = useState(false);
  const refresh = () => fetch("/api/runs").then((r) => r.json()).then((d) => { setRuns(d.runs); setRun(d.runs.find((x: Run) => x.fixtureId === "wrong-discount") ?? d.runs[0]); });
  useEffect(() => { refresh(); }, []);
  async function present() { setWorking(true); const response = await fetch("/api/runs/presentation", { method: "POST" }); const data = await response.json(); setRun(data.run); setRuns((current) => [data.run, ...current]); setWorking(false); }
  return <main className="shell"><header className="nav"><a href="/demo" className="brand">Proof<span>Ad</span></a><nav><a href="/app">App</a><a aria-current="page" href="/demo">Demo</a><a href="/evaluation">Evaluation</a></nav></header><section className="hero"><p className="eyebrow">EVALUATION WORKSPACE · PHASE A</p><h1>It looked right. The evaluation found the discount was wrong.</h1><p>ProofAd turns a reference image and three campaign fields into atomic, checkable requirements—not an unexplained score.</p><div className="callout"><strong>Evidence-source mode is locked.</strong> These are local deterministic fixtures, and the Presentation Run below creates a new saved fixture run.</div></section><section className="demo-grid"><div><h2>Phone placement preview</h2><div className="phone"><div className="notch" /><iframe title="ProofAd application preview" src="/app?embedded=1" /></div><p className="muted">Demonstration viewport only; this does not claim native-app or ad-platform compatibility.</p></div><div className="presentation"><p className="eyebrow">PRESENTATION RUN</p><h2>Start a fresh evaluation</h2><p>Shows Submitted → Checks Completed → Completed. In Phase A, this creates a new local fixture record. It does not replay a previous run as live.</p><button onClick={present} disabled={working}>{working ? "Creating local run…" : "Start Presentation Run"}</button><dl><dt>Phase A provider calls</dt><dd>0</dd><dt>Phase B allocation</dt><dd>1 generation + 1 visual evaluation, only after approval</dd></dl></div></section><section className="library"><h2>Test Runs library <span className="muted">8 core + 2 optional</span></h2><div className="run-list">{runs.map((item) => <button onClick={() => setRun(item)} className={run?.id === item.id ? "selected" : ""} key={item.id}><span>{item.name}</span><Badge verdict={item.verdict} /></button>)}</div></section>{run && <RunDetails run={run} />}</main>;
}
