"use client";
import { useEffect, useState } from "react";
import { RunDetails } from "@/components/run-details";
import type { Run } from "@/lib/types";

export default function AppPage() {
  const [runs, setRuns] = useState<Run[]>([]); const [selected, setSelected] = useState<Run | null>(null);
  useEffect(() => { fetch("/api/runs").then((r) => r.json()).then((d) => { setRuns(d.runs); setSelected(d.runs.find((x: Run) => x.fixtureId === "wrong-discount") ?? d.runs[0]); }); }, []);
  return <main className="shell"><header className="nav"><a href="/demo" className="brand">Proof<span>Ad</span></a><nav><a href="/app">App</a><a href="/demo">Demo</a><a href="/evaluation">Evaluation</a></nav></header><section className="hero compact"><p className="eyebrow">PHASE A · PROVIDER LOCKED</p><h1>Creative inspection you can explain.</h1><p>Describe the campaign, inspect the artifact, and see the evidence behind each decision.</p></section><section className="create"><div><h2>Create an inspection</h2><p className="muted">Phase A is fixture-only. The form previews the final contract; it cannot call Gemini.</p><label>Reference product<input disabled value="Northstar Sparkling Water reference.png" /></label><div className="form-grid"><label>Target geography<input disabled value="Bengaluru, India" /></label><label>Season<input disabled value="Monsoon" /></label></div><label>Exact required copy<input disabled value="20% OFF THIS WEEKEND" /></label><button disabled>Create Ad — live mode locked</button></div><aside className="contract"><h3>How we interpret your brief</h3><p>We freeze your original geography, season, literal campaign copy, reference identity, and criterion IDs before generation.</p><p>Fixture mode demonstrates the same result schema and decision policy without provider usage.</p></aside></section><section className="library"><h2>Saved test runs</h2><div className="run-list">{runs.map((run) => <button className={selected?.id === run.id ? "selected" : ""} onClick={() => setSelected(run)} key={run.id}><span>{run.name}</span><b>{run.verdict}</b></button>)}</div></section>{selected && <RunDetails run={selected} />}</main>;
}
